### ISSUE TITLE
How to see all classes relationship in the solution?

### ISSUE THREAD

**Issue by alexandis** [realvizu/softvis#14]
I don't want to add the classes one by one - there are too many. To get the idea about some new solution, I just want the tool to analyze whole solution (project) and build the diagram for me, including all relevant info.

**Comment by realvizu** [comment]
It's on the roadmap for the next release to add many files at once from the solution explorer to the diagram (see issue #9). Unfortunately I cannot predict a release date because it's a hobby project and I hardly have any time nowadays to work on it.

If you need to reverse engineer projects/solutions you can try Enterprise Architect, Visual Studio Enterprise Edition's CodeMap feature or ReSharper. All of them have trial versions too.
However generating a diagram with lots of info on it usually tends to be overwhelming and hard to comprehend. That never really works for me.
That's why I'm trying to adapt a different approach in Quick Diagram Tool: to put just a few items onto the diagram and then explore their relationships to other items by adding them to the diagram as you encounter them. So you can always focus on just a handful of items at a time. So I'm not sure that Quick Diagram Tool will ever be able to generate a diagram that includes all relevant info of a whole project/solution. But it's hard to tell since it's an experimental project.

**Comment by realvizu** [comment]
Closing this issue because this repo is going to be archived.
The successor of this tool is called Codartis Diagram Tool and is not OSS any more.
You can find it at: https://codartis.com
